export const posts = [
  {
    slug: "love",
    title: "Love",
    date: "2026-08-24",
    tags: ["science", "neuroscience", "society", "evolution"],
    excerpt: "A science-grounded reflection on romantic love, moving from sacrifice and subjective meaning to evolutionary biology, neuroscience, modern dating, and why love can feel so powerful.",
    content: `Dashrath Manjhi, was an Indian man who spent 22 years of his life cutting through a mountain with a hammer and a chisel. He did not work for a government, nor for a company. Neither did he receive any money to do so. 22 years earlier his wife got seriously injured while crossing the mountain, and lost her life as she could not receive medical treatment in time. The village was surrounded by mountainous terrain which made reaching important services extremely difficult, and it pushed the villagers to take difficult routes frequently. Dashrath, deeply affected by the incident, and the fear of someone going through what he had to go through, started beside his labour work to cut through the mountain and pave the path for a passage that allowed for the nearby services to be more accessible for the villagers. Despite being mocked and called crazy, his project was successful and is still being used to this day. He did not do it for a return, and he was aware that nothing would bring his wife back, but he was driven by a very deep feeling, that still pushes humans today to do crazy stuff, and that is (what people call) love. 

Poems have been written, music composed, novels and stories curved into stones, and movies made about it. Most of them in fact. All major religions today contain elements of love, some of which’s foundations are built on it. But why is it so powerful? Why are people willing to give their lives for love? And why is it important for the survival of us humans?

First, let’s be clear. “Love” alone is a vague term, and it can	 be expressed in many contexts. There is romantic love, material love, love for the land, spiritual love, love for an idea, and every time people get interested in something they decide to call it love. It is a very general term and each one of these forms might express different feelings, and incompatible neurological processes. But here we will only be focusing on one of them, in fact the most culturally celebrated of them all, you guessed it, romantic love, and every time “love” is mentioned from now on we are referring to this form of love.

You might have experienced love at some point, whether for a crush, a talking stage, or a partner. You think about them all the time, you live fantasies in you head, in fact, a whole love story that would earn a bestseller as a novel; anyways, you build a mental future together, you analyze their messages and replay the conversations in your mind, you worry about losing their attention, and you ignore flaws in them clearer than the sky. But have you ever asked yourself if what you call “love” (if you ever “loved” someone) is truly love or something else, maybe you haven’t experienced true “love” to know, and so, how can you be so sure about it.

“Love” is not something singular, and trying to define it (at least not scientifically) is highly subjective. Love encompasses a vast list of feelings and each with different levels of intensities, and so there is not a single right way to define it. It typically includes the feeling of attraction, emotional attachment, a desire for closeness, concern for the other person’s wellbeing, in addition to the feelings I mentioned earlier. 

The moment humans decided to capsulize the combination of these feelings in a single word is not fully known. But different cultures and humans across different times have expressed not necessarily the whole realm of love in a single word but separate words for each combination of the corresponding feelings and desires, and I’m pretty sure people had their ways of expressing their love even before language was developed. ANYWAYS, one of the earliest and well documented word for “love” is the Sumerian expression ki-aŋ (also written ki-ag, 𒆠𒉘), meaning “to love”(pronounced kee-ang) which was found in a text carved into limestone that dates roughly to 2450 BCE (a time not very far from when writing was invented by the way).

Until now we have only talked about the subjective definition of love. We did not answer the whys; why is it so powerful? Why are people willing to give their lives for love? And why is it important for the survival of us humans? To be able to answer these we need to explore the fundamental nature of love, and why we love. These can best be approached through neuroscience and evolutionary biology. 

Natural selection favors traits that increase the transmission of genes to future generations, and can sometimes lead to fascinating ways of reproduction. When we talk about the survival of a species, nature can lead to unusual reproductive strategies, in some cases it does not matter who survives from the parents, let alone the pleasure either of them get from the process (yeah... not everyone’s getting laid for the good time), all that matters is that the genes are being passed on to the next generation. 

A good example of that would be antechinus, a small mouse-like marsupial. The males of antechinus have one breeding season in their entire lives, and it lasts for a few weeks (aprox. 3 weeks), in which they have to find a female and mate. Due to the short timeline and high competition for reproductive opportunities, they sacrifice sleep, their physiology changes dramatically due to stress, and eventually the entire male population dies from the physiological consequences following the breeding period (including the unlucky ones who couldn’t find a mate). The next male population essentially consists entirely of the sons of the females (fascinating right?). Another example of male sacrifice would be the Australian redback spider, where the male gets consumed by the female while the mating continues, and this male cannibalism happens 65% of the time (literally dying just to score). Jokes aside, neither the antechinus nor the spider consciously decides they want to sacrifice their lives for their future children, nor do they seek the pleasure of the process, natural selection favored a behavior that increases reproductive success. Male antechinus invest everything to pass on their genes in this single breeding opportunity. The spider’s sacrifice gives him a greater success at fertilizing more of the female’s eggs and passing on more of his genes, while preserving his life for some hypothetical second female may have relatively little evolutionary value since finding another one is of extreme difficulty. Natural selection sticks with whatever strategy results in more genes being passed on.

Some salmon species spend their lives in the ocean, travel against the current of a river in the breeding season (usually the river they were born in), they stop feeding and devote their remaining energy for reproduction. After reaching their destination, the females lay their eggs and the males compete to fertilize them, then both the males and the females die within days. Another example (last one, I promise) is the bluebanded goby fish, in which the fish can change their sex in either direction. The fish compete for who will be the male, the more dominant becomes the male and the subordinate fish remains a female. This dominant male has more reproductive success, can mate with multiple females, and so can pass on his genes more extensively than he might have as a female. 

In some animal species, the male mates with the female while the female raises the offspring, in others, neither parent has to take care of the offspring, and in some, both parents raise the offspring until they are mature enough to survive on their own. Again, natural selection favors the behavior that passes the most genes. The list of examples goes on and on, and I wish I could add everything here, perhaps in another section I might add later. Anyhow, these are more than enough to make the point.

When it comes to humans, the offspring are so fragile, they cannot survive on their own, and in fact hold the record for the absolute duration of time spent dependent on parents, thanks to how much time it takes for our massive brains to develop. Living in the hard conditions of the past, depending on hunting and gathering for food, it would have been impossible for the mother to take care of the children and provide food and protection on her own, so the individuals who would pursue and stay with their reproductive partners had a greater chance of surviving and passing on their genes and so on. What was one of the things that made males and females want to stay together for so long despite all the responsibilities? Of course, love. As much as cooperation was the key to the success of our species, like hunting in a group and sharing resources, cooperating to raise the children together was also a major factor for our success, and love have played an important role in motivating partners to stay together and achieve that. 


Many of the characteristics that an individual finds lovable/attractive in a partner to this day are the ones that may have best contributed to the reproductive success and the raising of children in the past, and our biology still influences a lot of our decisions, and yes more than we think. Women still tend to find tall men with moderately masculine features more attractive, which might have been associated with the male being more capable of defending the partner and offspring from threats, and providing food. Men still tend to prefer a lower waist-to-hip ratio, feminine facial characteristics, and cues associated with youth and reproductive maturity, as these might have signaled fertility and health. Both look for someone who is caring, kind, warm, and trustworthy as they may have indicated that the partner would cooperate in raising the children, and that they would not abandon or endanger the family. Other characteristics include intelligence, ambition, and compatibility, major characteristics that were important for our survival and successful upbringing of offspring. 

It would also be worth mentioning that when it comes to choosing a partner, women tend to be more selective than men. As an evolutionary behavior hard wired to the subconscious (along with a conscious aspect, of course), it can be attributed to the fact that women carry on more biological investment and responsibilities. From pregnancy to lactation to the long-term parental care, choosing a partner wisely was and still is a life changing decision for a woman; it makes the difference between putting the family in danger and struggle, or living in comfort and raising healthy offspring. A bad choice, and all a man would invest in is a sperm, and a miserable life. As a matter of fact, in the U.S. (U.S. because otherwise traditions also play a huge role in this freedom) 69% of divorces are initiated by women.

Now let’s dive into the brain of someone in love.
What manifests as the feeling of being “in love” is the powerful interplay of chemical signals in the brain in the different stages of love; these include hormones and neurotransmitters such as dopamine (for reward and motivation), oxytocin (for bonding and attachment), serotonin (for mood and obsessive thinking), testosterone and estrogen (for sexual desire), norepinephrine (for excitement and alertness), and vasopressin (for pair-bonding and long-term attachment). Each of these plays their role in the different stages of love: the attraction, the butterflies, missing them although you have just seen them, the anxiety you get when they don’t respond, the attachment, and the urge to live your life with them, everything.

When we put someone in love for a brain scan, then mention their significant other, a rainbow of brain activity glows up. An example of that is when showing someone in the early romance stages a picture of their lover, the reward and motivation pathways similar to the ones strongly involved with the effects of addictive drugs like cocaine light up. Yeah, we should have more rehabilitation facilities for love withdrawal (please keep reading). Fascinating enough, when we let the participants who had been in a close relationship for some time make personality-traits judgement about themselves, their romantic partner, parents, and close friends, the same brain regions related to self-reference show distinctive engagement only when judging themselves and their romantic partner. This suggests that the neural representation of someone emotionally close to us overlaps with the processing of information about ourselves. And so yes, calling them your “other half” might be neurologically less ridiculous than it sounds.

After being rejected or going through a breakup, it can take a lot of time for activity in these neural pathways to return toward its previous state. You will still think about them a lot of the time, every face reminds you of them, you might even subconsciously look for someone that looks like them to feed the gap they left, you might feel lost and confused. Brain scans of people that have been recently rejected by a romantic partner, and who were deeply in love, show that the reward system has the same activity as being in love after showing them a picture of their exes, which is a plausible explanation of why “moving on” is very difficult and cannot simply happen by rationally telling yourself and accepting that they don’t want you. In another study on participants who had gone through an unwanted breakup in the last 6 months, thinking about their exes or being shown pictures of them showed high activity in the brain regions that overlap with when they were experiencing painful heat on their arms. So, the pain caused by a breakup can overlap with how physical pain is experienced, and saying “it hurts” might not be far from the truth. In another study, even when nothing about their previous relationship was shown, the more emotionally affected people showed less flexible and interconnected brain activity, which shows that the effects of a breakup may extend beyond moments when someone is thinking about their previous relationship.

With the modern socioeconomic structure we have been conditioned by, a lot of people are having to take into consideration an enormous number of factors before being able to make the decision to marry or build a life with someone; let alone the will to initiate a relationship. Maybe after I finish my university studies, secure a job, transition to a well paying job or perhaps wait for my startup to take off, secure a home and buy a car, afford the wedding costs, dye my hair to cover the gray, then I can commit. All these pressures are only delaying commitment and are making it easier for some to overlook relationships or postpone the thought of it. In Lebanon alone, the number of registered marriages dropped from 41236 in 2019 to 29004 in 2024, and some sources estimate the average age at first marriage for men and women increased from 28.5 and 23.2 in 1970 to 30.7 and 25.6, respectively, by 2019. 	

Beyond these socioeconomic pressures, the age of social media has also changed the concept of love tremendously. Social apps have become one of the most popular tools for dating and communication, where a significant proportion of modern relationships are being initiated online. These online platforms include dating apps like Tinder and Hinge, and social media platforms like Instagram, Facebook, and X; people are even getting to know each other through LinkedIn and video games like Minecraft and Roblox (and apparently language apps like Duolingo). 

Despite all these tools, modern dating and the concept of love have become more complex than ever. The paradox of choice explains the phenomena in which having more options can make decisions harder and less satisfying, and when it comes to dating and the infinite space of possible matches online platforms may offer, people are struggling to stick with someone and are always in the search of other possibilities. People can commonly say, “maybe if I put more effort into searching/dating, I can find the perfect one” so they never settle with someone, or they get less satisfied with their ongoing date or relationship because of the fact that there might always be someone better out there. Another problem is the content feeding us with unrealistic expectations of how love should be, depicting it like a list of features that should exist for it to be called love, or a list of variables and behaviors in someone that makes them lovable. In reality, nothing is perfect, even relationships, and the content shown almost always reflects the bright side of someone’s relationship, and social media is full of people faking it for the likes. The social media feed does not show the setbacks, the fights, the misunderstandings that can be part of any healthy relationship. It does not show the moments when the butterflies disappear and love stops feeling effortless, yet two people still choose each other anyway.

Love is powerful. It leads us to make unimaginable things, it constitutes an essential part of our lives, and occupies a huge part of our thinking. You might change your long-term plan for someone, you might change your character, values, habits, and goals. At the mercy of love, you act out of your biology instead of reason, you return to behaviors rooted in your evolutionary past. If I want to summarize why we love, why it is powerful and important, in one sentence, it is this:
 To help us have and raise children. 
 
So go love, and get some kiddos, and if you don’t want any, take the precautions.

References

- Bihar Tourism. [Dashrath Manjhi Memorial](https://tourism.bihar.gov.in/en/destinations/gaya/dashrath-manjhi).
- Electronic Pennsylvania Sumerian Dictionary. [ki aŋ [LOVE]: "to love"](https://oracc.museum.upenn.edu/epsd2/sux/o0031835).
- Zaid et al. (2024). [Semelparous marsupials reduce sleep for sex](https://www.cell.com/current-biology/fulltext/S0960-9822(23)01764-5). Current Biology.
- Andrade, M. C. B. (1996). [Sexual selection for male sacrifice in the Australian redback spider](https://www.jstor.org/stable/2890375). Science.
- NOAA Fisheries. [Fun facts about salmon: spawning, natal rivers and post-spawning death](https://www.fisheries.noaa.gov/national/outreach-and-education/fun-facts-about-amazing-atlantic-salmon).
- Rodgers, E. W., Earley, R. L., & Grober, M. S. (2007). [Social status determines sexual phenotype in the bidirectional sex-changing bluebanded goby](https://hero.epa.gov/reference/7883137). Journal of Fish Biology.
- Fletcher, G. J. O., Simpson, J. A., Campbell, L., & Overall, N. C. (2015). [Pair-bonding, romantic love, and evolution: The curious case of Homo sapiens](https://pubmed.ncbi.nlm.nih.gov/25910380/). Perspectives on Psychological Science.
- Walter et al. (2020). [Sex differences in mate preferences across 45 countries: A large-scale replication](https://pubmed.ncbi.nlm.nih.gov/32196435/). Psychological Science.
- Feingold, A. (1992). [Gender differences in mate-selection preferences: A test of the parental-investment model](https://pubmed.ncbi.nlm.nih.gov/1388281/). Psychological Bulletin.
- American Sociological Association. [Women more likely than men to initiate divorces, but not non-marital breakups](https://www.asanet.org/women-more-likely-men-initiate-divorces-not-non-marital-breakups/).
- de Boer, A., van Buel, E. M., & ter Horst, G. J. (2012). [Love is more than just a kiss: A neurobiological perspective on love and affection](https://pubmed.ncbi.nlm.nih.gov/22119059/). Neuroscience.
- Aron et al. (2005). [Reward, motivation, and emotion systems associated with early-stage intense romantic love](https://pubmed.ncbi.nlm.nih.gov/15928068/). Journal of Neurophysiology.
- Laurita et al. (2017). [Dissociable patterns of brain activity for mentalizing about known others](https://pubmed.ncbi.nlm.nih.gov/28407150/). Social Cognitive and Affective Neuroscience.
- Fisher et al. (2010). [Reward, addiction, and emotion-regulation systems associated with rejection in love](https://journals.physiology.org/doi/10.1152/jn.00784.2009). Journal of Neurophysiology.
- Kross et al. (2011). [Social rejection shares somatosensory representations with physical pain](https://www.pnas.org/doi/10.1073/pnas.1102693108). Proceedings of the National Academy of Sciences.
- Alonso Martínez et al. (2020). [Reduced spatiotemporal brain dynamics are associated with increased depressive symptoms after a relationship breakup](https://pubmed.ncbi.nlm.nih.gov/32516738/). NeuroImage: Clinical.
- Lebanese Central Administration of Statistics. [Vital Data 1999-2025: Births, deaths, marriages and divorces](https://www.opendatalebanon.org/en/data/vital-data-1999-2025-births-deaths-marriages-divorces).
- Central Administration of Statistics & International Labour Organization. [Labour Force and Household Living Conditions Survey 2018-2019](https://www.ilo.org/publications/labour-force-and-household-living-conditions-survey-lfhlcs-lebanon-2018).
- Rosenfeld, M. J., Thomas, R. J., & Hausen, S. (2019). [Disintermediating your friends: How online dating in the United States displaces other ways of meeting](https://www.pnas.org/doi/10.1073/pnas.1908630116). Proceedings of the National Academy of Sciences.
- Pronk, T. M., & Denissen, J. J. A. (2020). [A rejection mind-set: Choice overload in online dating](https://repository.tilburguniversity.edu/bitstreams/ebc42537-22e4-43fd-91cd-c8c69bc7fc19/download). Social Psychological and Personality Science.
`,
  },
  {
    slug: "the-science-of-existence",
    title: "The Science of Existence",
    date: "2026-06-01",
    tags: ["science", "philosophy"],
    excerpt: "An upcoming essay on what science can tell us about existence, and where its questions begin.",
    content: "This essay is currently in progress. Check back soon.",
  },
  {
    slug: "mentory",
    title: "Mentory",
    date: "2026-05-01",
    tags: ["learning", "growth"],
    excerpt: "An upcoming reflection on mentorship, memory, and the people who shape how we learn.",
    content: "This essay is currently in progress. Check back soon.",
  },
  {
    slug: "humans-and-conflicts",
    title: "Humans and Conflicts",
    date: "2026-06-23",
    tags: ["society", "history", "conflict"],
    excerpt: "A reflection on how conflict shaped early human societies and how our need for order eventually gave rise to leadership and institutions.",
    content: `Many things have changed with our fast-evolving civilization, we have come to set keystone principles and “common” standards that enabled us to expand our societies with an all the more coherent structure. Humanity’s need for something that would reduce conflicts between the individuals of its groups, such as the primitive muddle of distributing goods fairly between the members of a tribe, necessitated the direction of a leader. These leaders, or what are now known as politicians reach their positions in the name of setting and implementing such principles to improve their people’s lives. However, this ideal picture of a politician and this abstract motive is rarely carried, let alone the differences in the social or economic perspectives held by members of the same group, or the classist provisions where the ruling system discriminates between people of the society. Instead, it may be fame, influence, or wealth they are running after or the protection of a standpoint they foresee in reaching power. They are obliged to work in a systematic way as opposed to the country they serve, or to specific groups within that country that align with their judgments and perspectives, except, however, for the other cases mentioned, where the aim comes at containing the people and without considering the opinions of their contemporaries.


In 1984, as researchers in northern Spain were examining a site called the “Pit of Bones”, an ancient 42-foot-deep cave said to contain the remains of at least 28 people, they made an interesting discovery. Upon piecing one of the skulls, and applying a combination of dating techniques, they discovered that a 430,000-year-old Homo heidelbergensis, an early human ancestor, appeared to have been brutally smashed twice in the head and dropped down the cave; that, evidenced by two identical holes above the left eyebrow. Scientists on the site suggested that living in the harsh conditions of that time, with very limited resources, it is most likely that the conflict was over some food. This discovery besides being the earliest recorded murder in history, holds a deeper significance to our understanding of human nature and the advent of conflicts, which is the significant role that conflicts played in the natural selection mechanism that led to our evolution, where alongside other animals that competed for food, mates, and territory, only the ones with better survival strategies such as obtaining food at hard times and protecting the offspring, and sexually competitive like having stronger physical characteristics are the ones who were able to pass their genes and make us who we are.

With the domination of homo sapiens which developed complex social groups capable of cooperating to survive the hardest of environments, contrary to Neanderthals, their now-extinct ancestral counterparts who preferred living in small, isolated groups, societies started to emerge, requiring more advanced organizational systems which were also accompanied by a modernization in the notion of conflicts.

With the development of agriculture around 12,000 years ago, humans went from living in small, isolated nomadic societies focused on hunting and gathering for survival and having to follow the migration of animals and seasonal plant growth, to settling around fertile lands where they adopted farming as a more reliable and controllable food source.

As these settlements grew into larger communities, they turned into villages (in the modern sense) and some social structures required a leader which were typically local chieftains who usually helped distribute the harvests, and territory, and resolve any conflict between members of the community.

Coming soon.`,
  },
];
